"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Trash2, UserRoundCog } from "lucide-react";
import { NajahShell } from "@/components/NajahShell";
import { useAuth } from "@/lib/useAuth";
import { createBrowserSupabaseClient } from "@/lib/supabase-client";

const levels = [{ value: "3AC", label: "3e année collège" }, { value: "TRC", label: "Tronc commun" }, { value: "1BAC", label: "1ère année bac" }, { value: "2BAC", label: "2e année bac" }];
const tracks = ["Sciences mathématiques", "Sciences physiques", "Sciences de la vie et de la terre", "Lettres et sciences humaines"];
const regions = ["Rabat-Salé-Kénitra", "Casablanca-Settat", "Fès-Meknès", "Marrakech-Safi", "Tanger-Tétouan-Al Hoceïma", "Autre"];
export default function ProfilePage() {
  const { isAuthenticated, user } = useAuth(); const supabase = createBrowserSupabaseClient(); const [level, setLevel] = useState("2BAC"); const [track, setTrack] = useState(""); const [region, setRegion] = useState(""); const [pseudonym, setPseudonym] = useState(""); const [showPseudonym, setShow] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!user) return; supabase.from("student_profiles").select("level,track,region,pseudonym,show_pseudonym").eq("user_id", user.id).maybeSingle().then(({ data }) => { if (!data) return; setLevel(data.level ?? "2BAC"); setTrack(data.track ?? ""); setRegion(data.region ?? ""); setPseudonym(data.pseudonym ?? ""); setShow(data.show_pseudonym ?? true); }); }, [user]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const { error: saveError } = await supabase.from("student_profiles").upsert({ user_id: user!.id, level, track, region, pseudonym: pseudonym || null, show_pseudonym: showPseudonym, preferred_locale: "fr" }); setSaving(false); if (saveError) setError(saveError.message); else setSaved(true); };
  if (!isAuthenticated) return <NajahShell><div className="najah-card mx-auto max-w-xl p-12 text-center"><UserRoundCog className="mx-auto size-12 text-emerald-700" /><h1 className="mt-5 text-2xl font-black text-emerald-950">Votre profil scolaire</h1><a href="/auth" className="najah-button mt-6">Se connecter</a></div></NajahShell>;
  return <NajahShell><section><p className="section-kicker">Mon profil</p><h1 className="mt-2 text-4xl font-black text-emerald-950">Personnalisez votre espace.</h1><p className="mt-3 text-slate-600">Ces informations servent à filtrer vos archives et adapter vos révisions.</p></section><form onSubmit={save} className="najah-card mt-8 max-w-3xl p-7"><div className="grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-sm font-bold">Niveau<select value={level} onChange={e => setLevel(e.target.value)} className="najah-input">{levels.map(item => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="space-y-2 text-sm font-bold">Filière<select value={track} onChange={e => setTrack(e.target.value)} className="najah-input"><option value="">Choisir</option>{tracks.map(item => <option key={item}>{item}</option>)}</select></label><label className="space-y-2 text-sm font-bold sm:col-span-2">Académie / région<select value={region} onChange={e => setRegion(e.target.value)} className="najah-input"><option value="">Choisir</option>{regions.map(item => <option key={item}>{item}</option>)}</select></label><label className="space-y-2 text-sm font-bold">Nom public<input value={pseudonym} onChange={e => setPseudonym(e.target.value)} className="najah-input" placeholder="Optionnel" /></label></div><label className="mt-6 flex items-center justify-between rounded-2xl bg-emerald-50 p-4 text-sm font-bold text-emerald-950">Afficher mon nom public dans le classement<input type="checkbox" checked={showPseudonym} onChange={e => setShow(e.target.checked)} className="size-5 accent-emerald-700" /></label><button disabled={!track || !region || saving} className="najah-button mt-6 w-full disabled:opacity-50">{saving ? "Enregistrement…" : <><CheckCircle2 className="size-4" />Enregistrer mon profil</>}</button>{saved && <p className="mt-4 text-center text-sm font-bold text-emerald-700">Profil enregistré.</p>}{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}</form><section className="mt-6 max-w-3xl rounded-[28px] border border-red-200 bg-red-50 p-6"><h2 className="font-black text-red-950">Supprimer mon compte</h2><p className="mt-2 text-sm leading-6 text-red-900/75">Cette action supprime définitivement votre compte et les données associées.</p><button className="mt-4 flex items-center gap-2 rounded-xl bg-red-700 px-4 py-2.5 font-bold text-white"><Trash2 className="size-4" />Supprimer mon compte</button></section></NajahShell>;
}
