"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { DoorOpen, LockKeyhole, Plus, Radio, UsersRound } from "lucide-react";
import { NajahShell } from "@/components/NajahShell";
import { useAuth } from "@/lib/useAuth";
import { createBrowserSupabaseClient } from "@/lib/supabase-client";
import { labelForLevel, levels, subjects, type Level } from "@/lib/catalog";

type Room = { id: number; name: string; description: string | null; level: Level | null; subject: string | null; max_members: number };
export default function RoomsPage() { const { isAuthenticated, user } = useAuth(); const router = useRouter(); const [open, setOpen] = useState(false); const [rooms, setRooms] = useState<Room[]>([]); const supabase = createBrowserSupabaseClient(); useEffect(() => { supabase.from("study_rooms").select("id,name,description,level,subject,max_members").eq("kind", "open").order("created_at", { ascending: false }).then(({ data }) => setRooms(data ?? [])); }, []); return <NajahShell><section className="flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker">Réviser ensemble</p><h1 className="mt-2 text-4xl font-black text-emerald-950">Les salles ouvertes maintenant.</h1><p className="mt-3 max-w-2xl leading-7 text-slate-600">Concentrez-vous avec d’autres élèves. Les salles privées restent accessibles uniquement avec leur code.</p></div>{isAuthenticated ? <button onClick={() => setOpen(true)} className="najah-button"><Plus className="size-4" />Créer une salle</button> : <Link href="/auth" className="najah-button">Se connecter pour créer</Link>}</section><section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{rooms.length ? rooms.map(room => <article key={room.id} className="najah-card p-5"><div className="flex items-start justify-between"><span className="rounded-2xl bg-emerald-50 p-3 text-emerald-800"><UsersRound className="size-5" /></span><span className="inline-flex items-center gap-1 text-xs font-black text-emerald-700"><Radio className="size-3" />Ouverte</span></div><h2 className="mt-5 text-xl font-black text-emerald-950">{room.name}</h2><p className="mt-2 min-h-10 text-sm leading-6 text-slate-600">{room.description || "Salle de révision organisée."}</p><div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-100 px-2.5 py-1">{room.level ? labelForLevel[room.level] : "Tous niveaux"}</span>{room.subject && <span className="rounded-full bg-slate-100 px-2.5 py-1">{room.subject}</span>}<span className="rounded-full bg-slate-100 px-2.5 py-1">{room.max_members} places</span></div><Link href={`/rooms/${room.id}`} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 py-2.5 font-bold text-slate-700"><DoorOpen className="size-4" />Entrer dans la salle</Link></article>) : <div className="najah-card col-span-full border-dashed px-6 py-16 text-center"><UsersRound className="mx-auto size-10 text-emerald-700" /><h2 className="mt-4 text-xl font-black text-emerald-950">Aucune salle ouverte pour le moment</h2><p className="mt-2 text-sm text-slate-500">Créez la première salle pour votre groupe.</p></div>}</section>{open && user && <RoomForm onClose={() => setOpen(false)} onCreated={id => router.push(`/rooms/${id}`)} />}</NajahShell>; }
function RoomForm({ onClose, onCreated }: { onClose: () => void; onCreated: (id: number) => void }) { const supabase = createBrowserSupabaseClient(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [kind, setKind] = useState<"open" | "private">("open"); const [level, setLevel] = useState<Level | "">(""); const [subject, setSubject] = useState(""); const [accessCode, setAccessCode] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); const { data, error: err } = await supabase.rpc("create_study_room", { p_name: name, p_description: description || null, p_kind: kind, p_level: level || null, p_subject: subject || null, p_access_code: kind === "private" ? accessCode : null }); setPending(false); if (err) return setError(err.message); onCreated(data as number); }; return <div className="fixed inset-0 z-50 grid place-items-center bg-emerald-950/40 p-4" onClick={onClose}><form onClick={event => event.stopPropagation()} onSubmit={submit} className="najah-card w-full max-w-md space-y-4 p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-emerald-950">Créer une salle</h2><button type="button" onClick={onClose} className="text-sm font-bold text-slate-400">Fermer</button></div><input required value={name} onChange={e => setName(e.target.value)} placeholder="Nom de la salle" className="najah-input" /><textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Une courte description" className="najah-input min-h-24" /><div className="grid grid-cols-2 gap-3"><select value={kind} onChange={e => setKind(e.target.value as "open" | "private")} className="najah-input"><option value="open">Ouverte</option><option value="private">Privée</option></select><select value={level} onChange={e => setLevel(e.target.value as Level)} className="najah-input"><option value="">Niveau (optionnel)</option>{levels.map(v => <option key={v} value={v}>{labelForLevel[v]}</option>)}</select></div><select value={subject} onChange={e => setSubject(e.target.value)} className="najah-input"><option value="">Matière (optionnel)</option>{subjects.map(v => <option key={v}>{v}</option>)}</select>{kind === "private" && <input required minLength={4} type="password" value={accessCode} onChange={e => setAccessCode(e.target.value)} placeholder="Code d’accès" className="najah-input" />}<button disabled={pending} className="najah-button w-full disabled:opacity-50"><LockKeyhole className="size-4" />{pending ? "Création…" : "Créer la salle"}</button>{error && <p className="text-sm font-bold text-red-700">{error}</p>}</form></div>; }
