"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ChartNoAxesCombined, Clock3, Flame, Target, Trophy } from "lucide-react";
import { NajahShell } from "@/components/NajahShell";
import { useAuth } from "@/lib/useAuth";
import { createBrowserSupabaseClient } from "@/lib/supabase-client";

type Metrics = { studyMinutes: number; quizAccuracy: number; streakDays: number };
export default function DashboardPage() {
  const { isAuthenticated, user } = useAuth(); const supabase = createBrowserSupabaseClient(); const [metrics, setMetrics] = useState<Metrics>({ studyMinutes: 0, quizAccuracy: 0, streakDays: 0 });
  useEffect(() => { if (!user) return; (async () => { const [sessionsResult, attemptsResult] = await Promise.all([supabase.from("study_sessions").select("duration_minutes,started_at").eq("user_id", user.id), supabase.from("quiz_attempts").select("total_questions,correct_answers").eq("user_id", user.id)]); const sessions = sessionsResult.data ?? []; const attempts = attemptsResult.data ?? []; const total = attempts.reduce((sum, row) => sum + row.total_questions, 0); const correct = attempts.reduce((sum, row) => sum + row.correct_answers, 0); const days = new Set(sessions.map(row => new Date(row.started_at).toISOString().slice(0, 10))); let streak = 0; const cursor = new Date(); cursor.setUTCHours(0, 0, 0, 0); while (days.has(cursor.toISOString().slice(0, 10))) { streak++; cursor.setUTCDate(cursor.getUTCDate() - 1); } setMetrics({ studyMinutes: sessions.reduce((sum, row) => sum + row.duration_minutes, 0), quizAccuracy: total ? Math.round(correct / total * 100) : 0, streakDays: streak }); })(); }, [user]);
  if (!isAuthenticated) return <NajahShell><div className="najah-card mx-auto max-w-xl p-12 text-center"><ChartNoAxesCombined className="mx-auto size-12 text-emerald-700" /><h1 className="mt-5 text-2xl font-black text-emerald-950">Votre progression est privée</h1><p className="mt-2 text-slate-500">Connectez-vous pour retrouver vos statistiques.</p><Link href="/auth" className="najah-button mt-6">Se connecter</Link></div></NajahShell>;
  const hours = Math.floor(metrics.studyMinutes / 60); const minutes = metrics.studyMinutes % 60;
  return <NajahShell><section><p className="section-kicker">Mon espace</p><h1 className="mt-2 text-4xl font-black text-emerald-950">Bonjour, continuons à progresser.</h1><p className="mt-3 text-slate-600">Chaque session compte. Voici votre rythme actuel.</p></section><section className="mt-8 grid gap-4 md:grid-cols-3"><MetricCard label="Temps de révision" value={`${hours}h ${minutes}min`} icon={Clock3} /><MetricCard label="Série actuelle" value={`${metrics.streakDays} jour(s)`} icon={Flame} /><MetricCard label="Précision des quiz" value={`${metrics.quizAccuracy}%`} icon={Target} /></section><section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.85fr]"><article className="rounded-[30px] bg-emerald-950 p-7 text-white"><p className="section-kicker text-amber-200">Prochaine étape</p><h2 className="mt-2 text-3xl font-black">Reprenez là où vous vous êtes arrêté.</h2><p className="mt-3 max-w-md leading-7 text-emerald-50/75">Importez un support, demandez une explication ou lancez un quiz rapide.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/study" className="najah-button-gold">Ma séance</Link><Link href="/archive" className="rounded-2xl border border-white/20 px-5 py-3 font-black text-white">Les archives</Link></div></article><article className="najah-card p-6"><h2 className="flex items-center gap-2 text-xl font-black text-emerald-950"><Trophy className="size-5 text-amber-600" />Vos objectifs</h2><div className="mt-5 space-y-4"><div><div className="flex justify-between text-sm font-bold"><span>Importer un premier cours</span><span className="text-emerald-700">0%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-0 rounded-full bg-emerald-700" /></div></div><div><div className="flex justify-between text-sm font-bold"><span>Réussir un quiz</span><span className="text-emerald-700">0%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-0 rounded-full bg-amber-400" /></div></div></div></article></section></NajahShell>;
}
function MetricCard({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Clock3 }) { return <div className="najah-card p-5"><Icon className="size-5 text-emerald-700" /><p className="mt-3 text-2xl font-black text-emerald-950">{value}</p><p className="text-xs font-bold text-slate-500">{label}</p></div>; }
